name: Build and release Relazione
on:
  push:
    paths: 
      - 'relazione/**'
      - 'presentazione/**'
  workflow_dispatch:
  
jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile LaTeX (relazione)
        uses: xu-cheng/latex-action@v3
        with:
          working_directory : relazione
          root_file: relazione.tex
          latexmk_use_lualatex: true
      
      - name: Compile LaTeX (presentazione)
        uses: xu-cheng/latex-action@v3
        with:
          working_directory : presentazione
          root_file: presentazione.tex
          latexmk_use_lualatex: true

      - name: Get timestamp
        run: echo "TIMESTAMP=$(date +'%Y-%m-%d %T')" >> $GITHUB_ENV
      
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: Draft ${{ env.TIMESTAMP }}
          files: |
            relazione/relazione.pdf
            presentazione/presentazione.pdf
          draft: true